-- 0048_crm_dicionario_populado.sql
-- CRM Omnidesign — popula crm_dicionario (Fase 1, roadmap item 1 do
-- CRM_OMNIDESIGN_BLUEPRINT.md): erros/acertos do atendente (§3.2/3.3),
-- perfis do lead (§4.1), interesses (§6), qualificação (§5.2), objeções
-- (§8.2) e escalonamento por padrão (§9.1, E1/E2/E3/E6 — E4/E5/E7 são
-- regra de tempo/estado/score, não entram aqui).
--
-- Cada conceito tem forma oficial + variações coloquiais (lição do §11.2:
-- limiar de similaridade tem limite real, o dicionário precisa cobrir
-- múltiplas formas de escrita, não só o termo "correto").
--
-- idempotente: DELETE + INSERT por execução (evita duplicar padrão se a
-- migration rodar mais de uma vez).

DELETE FROM crm_dicionario WHERE categoria IN (
  'atendente_erro','atendente_acerto','perfil_lead','objecao','interesse','qualificacao','escalonamento'
);

INSERT INTO crm_dicionario (categoria, subtipo, padrao, tipo_match, peso, direcao_alvo, resposta_recomendada, dica_atendente) VALUES
  ('atendente_erro', 'tecnologia', 'wordpress', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'supabase', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'vercel', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'next.js', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'nextjs', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'github', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'hospedagem na', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'hospedado na', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'tecnologia', 'node.js', 'ilike', -15, 'enviada', NULL, 'Nunca cite tecnologia — "nossa infraestrutura própria"'),
  ('atendente_erro', 'preco_fechado_site', 'o site custa', 'ilike', -15, 'enviada', NULL, 'Site não tem preço fechado — "avaliar, mapear e orçar"'),
  ('atendente_erro', 'preco_fechado_site', 'site fica r$', 'ilike', -15, 'enviada', NULL, 'Site não tem preço fechado — "avaliar, mapear e orçar"'),
  ('atendente_erro', 'preco_fechado_site', 'site sai por', 'ilike', -15, 'enviada', NULL, 'Site não tem preço fechado — "avaliar, mapear e orçar"'),
  ('atendente_erro', 'preco_fechado_site', 'o valor do site é', 'ilike', -15, 'enviada', NULL, 'Site não tem preço fechado — "avaliar, mapear e orçar"'),
  ('atendente_erro', 'preco_fechado_site', 'site custa r$', 'ilike', -15, 'enviada', NULL, 'Site não tem preço fechado — "avaliar, mapear e orçar"'),
  ('atendente_erro', 'preco_fechado_site', 'o site sai r$', 'ilike', -15, 'enviada', NULL, 'Site não tem preço fechado — "avaliar, mapear e orçar"'),
  ('atendente_erro', 'desconto_proprio', 'te faço por', 'ilike', -20, 'enviada', NULL, 'Desconto é decisão do gestor — escalar antes de oferecer'),
  ('atendente_erro', 'desconto_proprio', 'consigo baixar', 'ilike', -20, 'enviada', NULL, 'Desconto é decisão do gestor — escalar antes de oferecer'),
  ('atendente_erro', 'desconto_proprio', 'desconto de', 'ilike', -20, 'enviada', NULL, 'Desconto é decisão do gestor — escalar antes de oferecer'),
  ('atendente_erro', 'desconto_proprio', 'consigo um desconto', 'ilike', -20, 'enviada', NULL, 'Desconto é decisão do gestor — escalar antes de oferecer'),
  ('atendente_erro', 'desconto_proprio', 'dou um desconto', 'ilike', -20, 'enviada', NULL, 'Desconto é decisão do gestor — escalar antes de oferecer'),
  ('atendente_erro', 'desconto_proprio', 'baixo o valor pra', 'ilike', -20, 'enviada', NULL, 'Desconto é decisão do gestor — escalar antes de oferecer'),
  ('atendente_erro', 'prazo_sem_validacao', 'fica pronto em', 'ilike', -10, 'enviada', NULL, 'Prazo só depois do levantamento'),
  ('atendente_erro', 'prazo_sem_validacao', 'semana que vem entrego', 'ilike', -10, 'enviada', NULL, 'Prazo só depois do levantamento'),
  ('atendente_erro', 'prazo_sem_validacao', 'é rápido', 'ilike', -10, 'enviada', NULL, 'Prazo só depois do levantamento'),
  ('atendente_erro', 'prazo_sem_validacao', 'fica pronto rapidinho', 'ilike', -10, 'enviada', NULL, 'Prazo só depois do levantamento'),
  ('atendente_erro', 'prazo_sem_validacao', 'entrego em poucos dias', 'ilike', -10, 'enviada', NULL, 'Prazo só depois do levantamento'),
  ('atendente_erro', 'promessa_integracao_terceiro', 'aprova rápido', 'ilike', -10, 'enviada', NULL, 'Aprovação de terceiros nunca é garantida'),
  ('atendente_erro', 'promessa_integracao_terceiro', 'instagram conecta na hora', 'ilike', -10, 'enviada', NULL, 'Aprovação de terceiros nunca é garantida'),
  ('atendente_erro', 'promessa_integracao_terceiro', 'a aprovação é rápida', 'ilike', -10, 'enviada', NULL, 'Aprovação de terceiros nunca é garantida'),
  ('atendente_erro', 'promessa_integracao_terceiro', 'é na hora mesmo', 'ilike', -10, 'enviada', NULL, 'Aprovação de terceiros nunca é garantida'),
  ('atendente_erro', 'minimiza_migracao', 'é fácil migrar', 'ilike', -10, 'enviada', NULL, 'Migração é serviço à parte, sempre'),
  ('atendente_erro', 'minimiza_migracao', 'levamos de graça', 'ilike', -10, 'enviada', NULL, 'Migração é serviço à parte, sempre'),
  ('atendente_erro', 'minimiza_migracao', 'a migração é rápida', 'ilike', -10, 'enviada', NULL, 'Migração é serviço à parte, sempre'),
  ('atendente_erro', 'minimiza_migracao', 'tiramos de lá fácil', 'ilike', -10, 'enviada', NULL, 'Migração é serviço à parte, sempre'),
  ('atendente_erro', 'linguagem_negativa', 'não dá', 'ilike', -5, 'enviada', NULL, 'Troque "não dá" por "vamos analisar o melhor caminho"'),
  ('atendente_erro', 'linguagem_negativa', 'impossível', 'ilike', -5, 'enviada', NULL, 'Troque "não dá" por "vamos analisar o melhor caminho"'),
  ('atendente_erro', 'linguagem_negativa', 'não fazemos isso', 'ilike', -5, 'enviada', NULL, 'Troque "não dá" por "vamos analisar o melhor caminho"'),
  ('atendente_erro', 'linguagem_negativa', 'não temos isso', 'ilike', -5, 'enviada', NULL, 'Troque "não dá" por "vamos analisar o melhor caminho"'),
  ('atendente_erro', 'linguagem_negativa', 'não conseguimos fazer', 'ilike', -5, 'enviada', NULL, 'Troque "não dá" por "vamos analisar o melhor caminho"'),
  ('atendente_acerto', 'pergunta_descoberta', 'me conta', 'ilike', 10, 'enviada', NULL, 'Vender depois de ouvir'),
  ('atendente_acerto', 'pergunta_descoberta', 'como funciona hoje', 'ilike', 10, 'enviada', NULL, 'Vender depois de ouvir'),
  ('atendente_acerto', 'pergunta_descoberta', 'qual seu objetivo', 'ilike', 10, 'enviada', NULL, 'Vender depois de ouvir'),
  ('atendente_acerto', 'pergunta_descoberta', 'o que você espera', 'ilike', 10, 'enviada', NULL, 'Vender depois de ouvir'),
  ('atendente_acerto', 'pergunta_descoberta', 'me fala um pouco', 'ilike', 10, 'enviada', NULL, 'Vender depois de ouvir'),
  ('atendente_acerto', 'pergunta_descoberta', 'como é hoje aí', 'ilike', 10, 'enviada', NULL, 'Vender depois de ouvir'),
  ('atendente_acerto', 'proximo_passo', 'posso te ligar', 'ilike', 10, 'enviada', NULL, 'Conversa nunca fica solta'),
  ('atendente_acerto', 'proximo_passo', 'te mando amanhã', 'ilike', 10, 'enviada', NULL, 'Conversa nunca fica solta'),
  ('atendente_acerto', 'proximo_passo', 'que horas fica bom', 'ilike', 10, 'enviada', NULL, 'Conversa nunca fica solta'),
  ('atendente_acerto', 'proximo_passo', 'posso te mandar', 'ilike', 10, 'enviada', NULL, 'Conversa nunca fica solta'),
  ('atendente_acerto', 'proximo_passo', 'vou te enviar hoje', 'ilike', 10, 'enviada', NULL, 'Conversa nunca fica solta'),
  ('atendente_acerto', 'proximo_passo', 'qual o melhor horário', 'ilike', 10, 'enviada', NULL, 'Conversa nunca fica solta'),
  ('atendente_acerto', 'linguagem_levantamento', 'vamos mapear', 'ilike', 10, 'enviada', NULL, 'Script certo do FAQ v3'),
  ('atendente_acerto', 'linguagem_levantamento', 'analisar sua necessidade', 'ilike', 10, 'enviada', NULL, 'Script certo do FAQ v3'),
  ('atendente_acerto', 'linguagem_levantamento', 'proposta com prazo e investimento', 'ilike', 10, 'enviada', NULL, 'Script certo do FAQ v3'),
  ('atendente_acerto', 'linguagem_levantamento', 'vamos entender sua necessidade', 'ilike', 10, 'enviada', NULL, 'Script certo do FAQ v3'),
  ('atendente_acerto', 'linguagem_levantamento', 'fazer um levantamento', 'ilike', 10, 'enviada', NULL, 'Script certo do FAQ v3'),
  ('perfil_lead', 'decidido', 'quero fechar', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'quando começa', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'me manda o contrato', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'urgente', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'pra ontem', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'bora fechar', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'pode começar', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'decidido', 'vamos fechar isso', 'ilike', 3, 'recebida', NULL, 'Não enrole: próximo passo concreto AGORA'),
  ('perfil_lead', 'pesquisador', 'tô vendo outras opções', 'ilike', 3, 'recebida', NULL, 'Prova social: mostrar projetos no ar'),
  ('perfil_lead', 'pesquisador', 'qual o diferencial', 'ilike', 3, 'recebida', NULL, 'Prova social: mostrar projetos no ar'),
  ('perfil_lead', 'pesquisador', 'me manda portfólio', 'ilike', 3, 'recebida', NULL, 'Prova social: mostrar projetos no ar'),
  ('perfil_lead', 'pesquisador', 'orçamento com outras', 'ilike', 3, 'recebida', NULL, 'Prova social: mostrar projetos no ar'),
  ('perfil_lead', 'pesquisador', 'to pesquisando', 'ilike', 3, 'recebida', NULL, 'Prova social: mostrar projetos no ar'),
  ('perfil_lead', 'pesquisador', 'comparando com outras empresas', 'ilike', 3, 'recebida', NULL, 'Prova social: mostrar projetos no ar'),
  ('perfil_lead', 'preco', 'quanto custa', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'tá caro', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'desconto', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'mais barato', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'promoção', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'qual o valor', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'quanto fica', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'preco', 'tem desconto', 'ilike', 3, 'recebida', NULL, 'Nunca brigar por preço. Valor + o que está incluso'),
  ('perfil_lead', 'desconfiado', 'já fui enganado', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'desconfiado', 'garantia', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'desconfiado', 'e se não funcionar', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'desconfiado', 'contrato', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'desconfiado', 'vocês existem mesmo', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'desconfiado', 'é confiável', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'desconfiado', 'tem cnpj', 'ilike', 3, 'recebida', NULL, 'Transparência total, clientes no ar, zero promessa inflada'),
  ('perfil_lead', 'ocupado', 'depois te falo', 'ilike', 3, 'recebida', NULL, 'Mensagens curtas, uma pergunta por vez'),
  ('perfil_lead', 'ocupado', 'corrido aqui', 'ilike', 3, 'recebida', NULL, 'Mensagens curtas, uma pergunta por vez'),
  ('perfil_lead', 'ocupado', 'vou ver', 'ilike', 3, 'recebida', NULL, 'Mensagens curtas, uma pergunta por vez'),
  ('perfil_lead', 'ocupado', 'sem tempo agora', 'ilike', 3, 'recebida', NULL, 'Mensagens curtas, uma pergunta por vez'),
  ('perfil_lead', 'ocupado', 'mais tarde te respondo', 'ilike', 3, 'recebida', NULL, 'Mensagens curtas, uma pergunta por vez'),
  ('perfil_lead', 'entusiasmado', 'e dá pra fazer também', 'ilike', 3, 'recebida', NULL, 'Anotar tudo, validar o essencial primeiro'),
  ('perfil_lead', 'entusiasmado', 'seria legal ter', 'ilike', 3, 'recebida', NULL, 'Anotar tudo, validar o essencial primeiro'),
  ('perfil_lead', 'entusiasmado', 'já pensei em app', 'ilike', 3, 'recebida', NULL, 'Anotar tudo, validar o essencial primeiro'),
  ('perfil_lead', 'entusiasmado', 'e também dava pra', 'ilike', 3, 'recebida', NULL, 'Anotar tudo, validar o essencial primeiro'),
  ('perfil_lead', 'entusiasmado', 'seria bacana', 'ilike', 3, 'recebida', NULL, 'Anotar tudo, validar o essencial primeiro'),
  ('objecao', 'preco', 'tá caro', 'ilike', 2, 'recebida', 'Reforçar o valor entregue e o que está incluso; revisar item a item com o cliente. Nunca oferecer desconto direto — escalar pro gestor.', 'Objeção de preço — nunca desconto direto'),
  ('objecao', 'preco', 'muito alto', 'ilike', 2, 'recebida', 'Reforçar o valor entregue e o que está incluso; revisar item a item com o cliente. Nunca oferecer desconto direto — escalar pro gestor.', 'Objeção de preço — nunca desconto direto'),
  ('objecao', 'preco', 'não cabe no orçamento', 'ilike', 2, 'recebida', 'Reforçar o valor entregue e o que está incluso; revisar item a item com o cliente. Nunca oferecer desconto direto — escalar pro gestor.', 'Objeção de preço — nunca desconto direto'),
  ('objecao', 'preco', 'tá salgado', 'ilike', 2, 'recebida', 'Reforçar o valor entregue e o que está incluso; revisar item a item com o cliente. Nunca oferecer desconto direto — escalar pro gestor.', 'Objeção de preço — nunca desconto direto'),
  ('objecao', 'preco', 'pesa no bolso', 'ilike', 2, 'recebida', 'Reforçar o valor entregue e o que está incluso; revisar item a item com o cliente. Nunca oferecer desconto direto — escalar pro gestor.', 'Objeção de preço — nunca desconto direto'),
  ('objecao', 'concorrente_mais_barato', 'mais barato', 'ilike', 2, 'recebida', 'Explicar que é proposta sob medida, não tabela genérica — comparar o que de fato está incluso em cada orçamento.', 'Comparar escopo, não só preço'),
  ('objecao', 'concorrente_mais_barato', 'outra agência', 'ilike', 2, 'recebida', 'Explicar que é proposta sob medida, não tabela genérica — comparar o que de fato está incluso em cada orçamento.', 'Comparar escopo, não só preço'),
  ('objecao', 'concorrente_mais_barato', 'concorrente', 'ilike', 2, 'recebida', 'Explicar que é proposta sob medida, não tabela genérica — comparar o que de fato está incluso em cada orçamento.', 'Comparar escopo, não só preço'),
  ('objecao', 'concorrente_mais_barato', 'outro orçamento', 'ilike', 2, 'recebida', 'Explicar que é proposta sob medida, não tabela genérica — comparar o que de fato está incluso em cada orçamento.', 'Comparar escopo, não só preço'),
  ('objecao', 'concorrente_mais_barato', 'recebi outro orçamento', 'ilike', 2, 'recebida', 'Explicar que é proposta sob medida, não tabela genérica — comparar o que de fato está incluso em cada orçamento.', 'Comparar escopo, não só preço'),
  ('objecao', 'sobrinho', 'sobrinho', 'ilike', 2, 'recebida', 'Diferenciar "fazer" de "manter no ar com suporte contínuo" — é isso que está sendo contratado.', 'Foco em manutenção/suporte, não só entrega inicial'),
  ('objecao', 'sobrinho', 'conhecido faz', 'ilike', 2, 'recebida', 'Diferenciar "fazer" de "manter no ar com suporte contínuo" — é isso que está sendo contratado.', 'Foco em manutenção/suporte, não só entrega inicial'),
  ('objecao', 'sobrinho', 'amigo cobra', 'ilike', 2, 'recebida', 'Diferenciar "fazer" de "manter no ar com suporte contínuo" — é isso que está sendo contratado.', 'Foco em manutenção/suporte, não só entrega inicial'),
  ('objecao', 'sobrinho', 'um amigo meu faz', 'ilike', 2, 'recebida', 'Diferenciar "fazer" de "manter no ar com suporte contínuo" — é isso que está sendo contratado.', 'Foco em manutenção/suporte, não só entrega inicial'),
  ('objecao', 'sobrinho', 'tenho um conhecido que mexe com isso', 'ilike', 2, 'recebida', 'Diferenciar "fazer" de "manter no ar com suporte contínuo" — é isso que está sendo contratado.', 'Foco em manutenção/suporte, não só entrega inicial'),
  ('objecao', 'so_instagram', 'só instagram', 'ilike', 2, 'recebida', 'Mostrar valor de canal próprio: sem depender de algoritmo, integra com gestão do negócio.', 'Canal próprio vs. dependência de rede social'),
  ('objecao', 'so_instagram', 'rede social basta', 'ilike', 2, 'recebida', 'Mostrar valor de canal próprio: sem depender de algoritmo, integra com gestão do negócio.', 'Canal próprio vs. dependência de rede social'),
  ('objecao', 'so_instagram', 'já tenho instagram', 'ilike', 2, 'recebida', 'Mostrar valor de canal próprio: sem depender de algoritmo, integra com gestão do negócio.', 'Canal próprio vs. dependência de rede social'),
  ('objecao', 'so_instagram', 'uso só o insta', 'ilike', 2, 'recebida', 'Mostrar valor de canal próprio: sem depender de algoritmo, integra com gestão do negócio.', 'Canal próprio vs. dependência de rede social'),
  ('objecao', 'so_instagram', 'o instagram já resolve', 'ilike', 2, 'recebida', 'Mostrar valor de canal próprio: sem depender de algoritmo, integra com gestão do negócio.', 'Canal próprio vs. dependência de rede social'),
  ('objecao', 'vou_pensar', 'vou pensar', 'ilike', 2, 'recebida', 'Perguntar abertamente o que ficou em dúvida e combinar um prazo de retorno.', 'Descobrir a dúvida real, não deixar solto'),
  ('objecao', 'vou_pensar', 'depois te falo', 'ilike', 2, 'recebida', 'Perguntar abertamente o que ficou em dúvida e combinar um prazo de retorno.', 'Descobrir a dúvida real, não deixar solto'),
  ('objecao', 'vou_pensar', 'vou ver', 'ilike', 2, 'recebida', 'Perguntar abertamente o que ficou em dúvida e combinar um prazo de retorno.', 'Descobrir a dúvida real, não deixar solto'),
  ('objecao', 'vou_pensar', 'deixa eu pensar', 'ilike', 2, 'recebida', 'Perguntar abertamente o que ficou em dúvida e combinar um prazo de retorno.', 'Descobrir a dúvida real, não deixar solto'),
  ('objecao', 'vou_pensar', 'vou avaliar com calma', 'ilike', 2, 'recebida', 'Perguntar abertamente o que ficou em dúvida e combinar um prazo de retorno.', 'Descobrir a dúvida real, não deixar solto'),
  ('objecao', 'sem_tempo', 'corrido', 'ilike', 2, 'recebida', 'Reforçar que o time cuida de tudo, o cliente só aprova — propor um horário específico.', 'Propor horário concreto, reduzir esforço do cliente'),
  ('objecao', 'sem_tempo', 'sem tempo', 'ilike', 2, 'recebida', 'Reforçar que o time cuida de tudo, o cliente só aprova — propor um horário específico.', 'Propor horário concreto, reduzir esforço do cliente'),
  ('objecao', 'sem_tempo', 'depois eu vejo', 'ilike', 2, 'recebida', 'Reforçar que o time cuida de tudo, o cliente só aprova — propor um horário específico.', 'Propor horário concreto, reduzir esforço do cliente'),
  ('objecao', 'sem_tempo', 'tô sem tempo agora', 'ilike', 2, 'recebida', 'Reforçar que o time cuida de tudo, o cliente só aprova — propor um horário específico.', 'Propor horário concreto, reduzir esforço do cliente'),
  ('objecao', 'sem_tempo', 'muito ocupado esses dias', 'ilike', 2, 'recebida', 'Reforçar que o time cuida de tudo, o cliente só aprova — propor um horário específico.', 'Propor horário concreto, reduzir esforço do cliente'),
  ('objecao', 'ja_fui_enganado', 'enganado', 'ilike', 2, 'recebida', 'Transparência total: mostrar clientes reais no ar, sem prometer nada além do combinado.', 'Prova social concreta, zero promessa inflada'),
  ('objecao', 'ja_fui_enganado', 'golpe', 'ilike', 2, 'recebida', 'Transparência total: mostrar clientes reais no ar, sem prometer nada além do combinado.', 'Prova social concreta, zero promessa inflada'),
  ('objecao', 'ja_fui_enganado', 'a agência sumiu', 'ilike', 2, 'recebida', 'Transparência total: mostrar clientes reais no ar, sem prometer nada além do combinado.', 'Prova social concreta, zero promessa inflada'),
  ('objecao', 'ja_fui_enganado', 'já caí em golpe', 'ilike', 2, 'recebida', 'Transparência total: mostrar clientes reais no ar, sem prometer nada além do combinado.', 'Prova social concreta, zero promessa inflada'),
  ('objecao', 'ja_fui_enganado', 'me enrolaram', 'ilike', 2, 'recebida', 'Transparência total: mostrar clientes reais no ar, sem prometer nada além do combinado.', 'Prova social concreta, zero promessa inflada'),
  ('objecao', 'resultado_antes_pagar', 'só pago se', 'ilike', 2, 'recebida', 'Explicar o modelo de trabalho: escopo claro definido antes, acompanhamento durante todo o processo.', 'Explicar modelo de trabalho sério, com escopo claro'),
  ('objecao', 'resultado_antes_pagar', 'resultado primeiro', 'ilike', 2, 'recebida', 'Explicar o modelo de trabalho: escopo claro definido antes, acompanhamento durante todo o processo.', 'Explicar modelo de trabalho sério, com escopo claro'),
  ('objecao', 'resultado_antes_pagar', 'quero ver funcionando antes', 'ilike', 2, 'recebida', 'Explicar o modelo de trabalho: escopo claro definido antes, acompanhamento durante todo o processo.', 'Explicar modelo de trabalho sério, com escopo claro'),
  ('objecao', 'resultado_antes_pagar', 'só fecho vendo resultado', 'ilike', 2, 'recebida', 'Explicar o modelo de trabalho: escopo claro definido antes, acompanhamento durante todo o processo.', 'Explicar modelo de trabalho sério, com escopo claro'),
  ('objecao', 'empresa_pequena', 'empresa de vocês é grande', 'ilike', 2, 'recebida', 'Reforçar equipe dedicada e atendimento próximo — mostrar projetos reais no ar como prova.', 'Atendimento próximo como vantagem, não desvantagem'),
  ('objecao', 'empresa_pequena', 'quantos funcionários', 'ilike', 2, 'recebida', 'Reforçar equipe dedicada e atendimento próximo — mostrar projetos reais no ar como prova.', 'Atendimento próximo como vantagem, não desvantagem'),
  ('objecao', 'empresa_pequena', 'vocês são poucos', 'ilike', 2, 'recebida', 'Reforçar equipe dedicada e atendimento próximo — mostrar projetos reais no ar como prova.', 'Atendimento próximo como vantagem, não desvantagem'),
  ('objecao', 'faco_eu_mesmo', 'wix', 'ilike', 2, 'recebida', 'Valorizar o tempo do cliente — manter no ar, seguro e atualizado é a parte difícil, não a montagem inicial.', 'Foco em manutenção contínua como o real trabalho'),
  ('objecao', 'faco_eu_mesmo', 'canva', 'ilike', 2, 'recebida', 'Valorizar o tempo do cliente — manter no ar, seguro e atualizado é a parte difícil, não a montagem inicial.', 'Foco em manutenção contínua como o real trabalho'),
  ('objecao', 'faco_eu_mesmo', 'eu mesmo faço', 'ilike', 2, 'recebida', 'Valorizar o tempo do cliente — manter no ar, seguro e atualizado é a parte difícil, não a montagem inicial.', 'Foco em manutenção contínua como o real trabalho'),
  ('objecao', 'faco_eu_mesmo', 'wordpress grátis', 'ilike', 2, 'recebida', 'Valorizar o tempo do cliente — manter no ar, seguro e atualizado é a parte difícil, não a montagem inicial.', 'Foco em manutenção contínua como o real trabalho'),
  ('objecao', 'faco_eu_mesmo', 'faço no wix mesmo', 'ilike', 2, 'recebida', 'Valorizar o tempo do cliente — manter no ar, seguro e atualizado é a parte difícil, não a montagem inicial.', 'Foco em manutenção contínua como o real trabalho'),
  ('objecao', 'faco_eu_mesmo', 'monto sozinho', 'ilike', 2, 'recebida', 'Valorizar o tempo do cliente — manter no ar, seguro e atualizado é a parte difícil, não a montagem inicial.', 'Foco em manutenção contínua como o real trabalho'),
  ('interesse', 'site_institucional', 'preciso de um site', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'site_institucional', 'quero um site', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'site_institucional', 'site novo', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'site_institucional', 'página pra minha empresa', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'site_institucional', 'presença online', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_ads', 'google ads', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_ads', 'adwords', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_ads', 'patrocinado no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_ads', 'aparecer no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_ads', 'anúncio no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_ads', 'anuncio no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'chatgpt_ads', 'chatgpt', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'chatgpt_ads', 'gpt ads', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'chatgpt_ads', 'anúncio na ia', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'chatgpt_ads', 'anunciar no chat gpt', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'chatgpt_ads', 'openai', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'chatgpt_ads', 'anuncio no chatgpt', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'trafego_pago_generico', 'anúncio', 'ilike', 1, 'recebida', NULL, 'Gatilho pra perguntar qual canal — não é serviço final'),
  ('interesse', 'trafego_pago_generico', 'tráfego', 'ilike', 1, 'recebida', NULL, 'Gatilho pra perguntar qual canal — não é serviço final'),
  ('interesse', 'trafego_pago_generico', 'impulsionar', 'ilike', 1, 'recebida', NULL, 'Gatilho pra perguntar qual canal — não é serviço final'),
  ('interesse', 'trafego_pago_generico', 'mídia paga', 'ilike', 1, 'recebida', NULL, 'Gatilho pra perguntar qual canal — não é serviço final'),
  ('interesse', 'trafego_pago_generico', 'midia paga', 'ilike', 1, 'recebida', NULL, 'Gatilho pra perguntar qual canal — não é serviço final'),
  ('interesse', 'google_meu_negocio', 'google meu negócio', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_meu_negocio', 'perfil no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_meu_negocio', 'avaliações no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_meu_negocio', 'aparecer no maps', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'google_meu_negocio', 'google meu negocio', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'manutencao_site', 'meu site quebrou', 'ilike', 2, 'recebida', NULL, 'Manutenção já está inclusa na hospedagem — argumento de conversão, não produto separado'),
  ('interesse', 'manutencao_site', 'site fora do ar', 'ilike', 2, 'recebida', NULL, 'Manutenção já está inclusa na hospedagem — argumento de conversão, não produto separado'),
  ('interesse', 'manutencao_site', 'atualizar meu site', 'ilike', 2, 'recebida', NULL, 'Manutenção já está inclusa na hospedagem — argumento de conversão, não produto separado'),
  ('interesse', 'manutencao_site', 'site tá lento', 'ilike', 2, 'recebida', NULL, 'Manutenção já está inclusa na hospedagem — argumento de conversão, não produto separado'),
  ('interesse', 'manutencao_site', 'site caiu', 'ilike', 2, 'recebida', NULL, 'Manutenção já está inclusa na hospedagem — argumento de conversão, não produto separado'),
  ('interesse', 'manutencao_site', 'site com erro', 'ilike', 2, 'recebida', NULL, 'Manutenção já está inclusa na hospedagem — argumento de conversão, não produto separado'),
  ('interesse', 'modulos_gestao', 'controle financeiro', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'modulos_gestao', 'financeiro', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'modulos_gestao', 'estoque', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'modulos_gestao', 'cadastro de cliente', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'modulos_gestao', 'sistema de gestão', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'modulos_gestao', 'sistema de gestao', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'sob_medida', 'sistema próprio', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'sob_medida', 'automação', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'sob_medida', 'integração', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'sob_medida', 'algo específico', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'sob_medida', 'sistema sob medida', 'ilike', 2, 'recebida', NULL, NULL),
  ('interesse', 'sob_medida', 'preciso de algo diferente', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'tem_site', 'não temos site', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'tem_site', 'nosso site é', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'tem_site', 'só tenho instagram mesmo', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'objetivo_principal', 'quero vender mais', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'objetivo_principal', 'aparecer no google', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'objetivo_principal', 'organizar a gestão', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'objetivo_principal', 'quero mais clientes', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'objetivo_principal', 'quero organizar a empresa', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'urgencia_prazo', 'pra esse mês', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'urgencia_prazo', 'sem pressa', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'urgencia_prazo', 'é urgente', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'urgencia_prazo', 'quero pra já', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'urgencia_prazo', 'sem prazo definido', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'quem_decide', 'vou falar com meu sócio', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'quem_decide', 'eu que decido', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'quem_decide', 'minha esposa cuida disso', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'quem_decide', 'meu sócio decide', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'quem_decide', 'quem decide sou eu', 'ilike', 2, 'recebida', NULL, NULL),
  ('qualificacao', 'faixa_investimento', 'orçamento de', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'faixa_investimento', 'posso investir até', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'faixa_investimento', 'tenho um orçamento de', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'concorrente_citado', 'a outra agência', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'concorrente_citado', 'recebi orçamento de', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'concorrente_citado', 'já falei com outra empresa', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'sistema_legado', 'uso planilha', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'sistema_legado', 'tenho um sistema', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'sistema_legado', 'uso erp', 'ilike', 1, 'recebida', NULL, NULL),
  ('qualificacao', 'sistema_legado', 'uso excel pra controlar', 'ilike', 1, 'recebida', NULL, NULL),
  ('escalonamento', 'pedido_desconto', 'me dá um desconto', 'ilike', 5, 'recebida', NULL, 'E1 — Escalar antes de responder a pedido de desconto'),
  ('escalonamento', 'pedido_desconto', 'faz por menos', 'ilike', 5, 'recebida', NULL, 'E1 — Escalar antes de responder a pedido de desconto'),
  ('escalonamento', 'pedido_desconto', 'consegue baixar', 'ilike', 5, 'recebida', NULL, 'E1 — Escalar antes de responder a pedido de desconto'),
  ('escalonamento', 'pedido_desconto', 'dá pra fazer mais em conta', 'ilike', 5, 'recebida', NULL, 'E1 — Escalar antes de responder a pedido de desconto'),
  ('escalonamento', 'reclamacao', 'péssimo', 'ilike', 5, 'recebida', NULL, 'E2 — Reclamação, escalar imediatamente'),
  ('escalonamento', 'reclamacao', 'absurdo', 'ilike', 5, 'recebida', NULL, 'E2 — Reclamação, escalar imediatamente'),
  ('escalonamento', 'reclamacao', 'procon', 'ilike', 5, 'recebida', NULL, 'E2 — Reclamação, escalar imediatamente'),
  ('escalonamento', 'reclamacao', 'quero cancelar', 'ilike', 5, 'recebida', NULL, 'E2 — Reclamação, escalar imediatamente'),
  ('escalonamento', 'reclamacao', 'vou no procon', 'ilike', 5, 'recebida', NULL, 'E2 — Reclamação, escalar imediatamente'),
  ('escalonamento', 'reclamacao', 'isso é um absurdo', 'ilike', 5, 'recebida', NULL, 'E2 — Reclamação, escalar imediatamente'),
  ('escalonamento', 'mudanca_escopo', 'quero adicionar', 'ilike', 5, 'recebida', NULL, 'E3 — Mudança de escopo em cliente ativo'),
  ('escalonamento', 'mudanca_escopo', 'muda aquilo que combinamos', 'ilike', 5, 'recebida', NULL, 'E3 — Mudança de escopo em cliente ativo'),
  ('escalonamento', 'mudanca_escopo', 'quero mudar o que foi combinado', 'ilike', 5, 'recebida', NULL, 'E3 — Mudança de escopo em cliente ativo'),
  ('escalonamento', 'mudanca_escopo', 'quero incluir mais uma coisa', 'ilike', 5, 'recebida', NULL, 'E3 — Mudança de escopo em cliente ativo'),
  ('escalonamento', 'juridico', 'multa', 'ilike', 5, 'recebida', NULL, 'E6 — Pergunta jurídica/contratual'),
  ('escalonamento', 'juridico', 'rescisão', 'ilike', 5, 'recebida', NULL, 'E6 — Pergunta jurídica/contratual'),
  ('escalonamento', 'juridico', 'cláusula', 'ilike', 5, 'recebida', NULL, 'E6 — Pergunta jurídica/contratual'),
  ('escalonamento', 'juridico', 'jurídico', 'ilike', 5, 'recebida', NULL, 'E6 — Pergunta jurídica/contratual'),
  ('escalonamento', 'juridico', 'falar com advogado', 'ilike', 5, 'recebida', NULL, 'E6 — Pergunta jurídica/contratual');
